package com.oracle.xmlns.inbound.ws_siec_actualizarestadodemensajesinbound;
// This source file is generated by Oracle tools.
// Contents may be subject to change.

import co.com.amx.siec.etadirect.ws_siec_actualizarestadodemensajesinbound.TypesetMessageStatusRequestData;

// For reporting problems, use the following:
// Generated by Oracle JDeveloper 12c 12.2.1.2.0.1648
public class WS_SIEC_ActualizarEstadoDeMensajesInbound_ptClient {
    public static void main(String[] args) {
        WSSIECActualizarEstadoDeMensajesInboundClientEp wSSIECActualizarEstadoDeMensajesInboundClientEp =
            new WSSIECActualizarEstadoDeMensajesInboundClientEp();
        WSSIECActualizarEstadoDeMensajesInboundInterface wSSIECActualizarEstadoDeMensajesInboundInterface =
            wSSIECActualizarEstadoDeMensajesInboundClientEp.getWSSIECActualizarEstadoDeMensajesInboundPt();
        TypesetMessageStatusRequestData body = null;
        // Add your code to call the desired methods.
wSSIECActualizarEstadoDeMensajesInboundInterface.actualizarEstadoDeMensajes(body);


    }
}
