
package com.oracle.xmlns.inbound.ws_siec_actualizarestadodemensajesinbound;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

import javax.xml.bind.annotation.XmlSeeAlso;

import co.com.amx.siec.etadirect.ws_siec_actualizarestadodemensajesinbound.ObjectFactory;
import co.com.amx.siec.etadirect.ws_siec_actualizarestadodemensajesinbound.TypesetMessageStatusRequestData;
import co.com.amx.siec.etadirect.ws_siec_actualizarestadodemensajesinbound.TypesetMessageStatusResponseData;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebService(name = "WS_SIEC_ActualizarEstadoDeMensajesInboundInterface",
            targetNamespace = "http://xmlns.oracle.com/Inbound/WS_SIEC_ActualizarEstadoDeMensajesInbound")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({ ObjectFactory.class })
public interface WSSIECActualizarEstadoDeMensajesInboundInterface {


    /**
     *
     * @param body
     * @return
     *     returns co.com.amx.siec.etadirect.ws_siec_actualizarestadodemensajesinbound.TypesetMessageStatusResponseData
     */
    @WebMethod(operationName = "ActualizarEstadoDeMensajes", action = "ActualizarEstadoDeMensajes")
    @WebResult(name = "actualizarEstadoMensaje_response",
               targetNamespace = "http://www.amx.com.co/SIEC/ETAdirect/WS_SIEC_ActualizarEstadoDeMensajesInbound",
               partName = "body")
    public TypesetMessageStatusResponseData actualizarEstadoDeMensajes(@WebParam(name =
                                                                                 "actualizarEstadoMensaje_request",
                                                                                 targetNamespace =
                                                                                 "http://www.amx.com.co/SIEC/ETAdirect/WS_SIEC_ActualizarEstadoDeMensajesInbound",
                                                                                 partName = "body")
                                                                       TypesetMessageStatusRequestData body);

}
