//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.13 at 11:05:18 AM COT 
//
package co.com.claro.wsorder.vo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for TypeDataResponseElement complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="TypeDataResponseElement">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="commands" type="{http://www.amx.com.co/SIEC/ETAdirect/WS_SIEC_ActualizarActividadesDeFacturacionMGWInbound}TypeCommandsResponseArray" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TypeDataResponseElement", propOrder = {
    "commands"
})
public class TypeDataResponseElement {

    protected TypeCommandsResponseArray commands;

    /**
     * Gets the value of the commands property.
     *
     * @return possible object is {@link TypeCommandsResponseArray }
     *
     */
    public TypeCommandsResponseArray getCommands() {
        return commands;
    }

    /**
     * Sets the value of the commands property.
     *
     * @param value allowed object is {@link TypeCommandsResponseArray }
     *
     */
    public void setCommands(TypeCommandsResponseArray value) {
        this.commands = value;
    }

    @Override
    public String toString() {
        return "TypeDataResponseElement [commands=" + commands + "]";
    }

}
