//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.13 at 11:05:18 AM COT 
//
package co.com.claro.wsorder.vo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for TypeUserElement complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="TypeUserElement">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="now" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="login" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="company" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="auth_string" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TypeUserElement", propOrder = {
    "now",
    "login",
    "company",
    "authString"
})
public class TypeUserElement {

    @XmlElement(required = true)
    protected String now;
    @XmlElement(required = true)
    protected String login;
    @XmlElement(required = true)
    protected String company;
    @XmlElement(name = "auth_string", required = true)
    protected String authString;

    /**
     * Gets the value of the now property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getNow() {
        return now;
    }

    /**
     * Sets the value of the now property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setNow(String value) {
        this.now = value;
    }

    /**
     * Gets the value of the login property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getLogin() {
        return login;
    }

    /**
     * Sets the value of the login property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setLogin(String value) {
        this.login = value;
    }

    /**
     * Gets the value of the company property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getCompany() {
        return company;
    }

    /**
     * Sets the value of the company property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setCompany(String value) {
        this.company = value;
    }

    /**
     * Gets the value of the authString property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getAuthString() {
        return authString;
    }

    /**
     * Sets the value of the authString property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setAuthString(String value) {
        this.authString = value;
    }

    @Override
    public String toString() {
        return "TypeUserElement [now=" + now + ", login=" + login
                + ", company=" + company + "]";
    }

}
